CREATE TABLE col_stress (
  id INTEGER,
user_id VARCHAR,
  date TEXT(10),
  irritabilité INTEGER(1),
  sentiments_depressifs INTEGER(1),
  bouche_seche_ou_gorge_seche INTEGER(1),
  actions_ou_gestes_impulsifs INTEGER(1),
  grincement_des_dents INTEGER(1),
  difficulte_a_rester_assis INTEGER(1),
  cauchemars INTEGER(1),
  diarrhee INTEGER(1),
  attaques_verbales_envers_quelquun INTEGER(1),
  hauts_et_bas_emotifs INTEGER(1),
  grande_envie_de_pleurer INTEGER(1),
  grande_envie_de_fuir INTEGER(1),
  grande_envie_de_faire_mal INTEGER(1),
  pensees_embrouillees INTEGER(1),
  debit_plus_rapide INTEGER(1),
  fatigue_ou_lourdeur_generalisees INTEGER(1),
  sentiment_detre_surchargee INTEGER(1),
  sentiment_detre_emotivement_fragile INTEGER(1),
  sentiment_de_tristesse INTEGER(1),
  sentiment_danxiete INTEGER(1),
  tension_emotionnelle INTEGER(1),
  hostilite_envers_les_autres INTEGER(1),
  tremblements_ou_gestes_nerveux INTEGER(1),
  begaiements_ou_hesitations_verbales INTEGER(1),
  incapacite_ou_difficulte_a_se_concentrer INTEGER(1),
  difficulte_a_organiser_ses_pensees INTEGER(1),
  difficulte_a_dormir_toute_la_nuit_sans_se_reveiller INTEGER(1),
  besoin_frequent_duriner INTEGER(1),
  maux_destomac_ou_difficultes_a_digerer INTEGER(1),
  geste_ou_sentiment_dimpatience INTEGER(1),
  maux_de_tete INTEGER(1),
  douleurs_au_dos_ou_a_la_nuque INTEGER(1),
  perte_ou_gain_dappetit INTEGER(1),
  perte_dinteret_pour_le_sexe INTEGER(1),
  oublis_frequents INTEGER(1),
  douleurs_ou_serrements_a_la_poitrine INTEGER(1),
  conflits_significatifs_avec_les_autres INTEGER(1),
  difficultes_a_se_lever_apres_le_sommeil INTEGER(1),
  sentiment_que_les_choses_sont_hors_de_controle INTEGER(1),
  difficulte_a_faire_une_longue_activite_continue INTEGER(1),
  mouvements_de_retrait_disolement INTEGER(1),
  difficulte_a_sendormir INTEGER(1),
  difficulte_a_se_remettre_dun_evenement_contrariant INTEGER(1),
  mains_moites INTEGER(1),
  total_de_limpact_du_stress_dans_votre_vie_actuelle INTEGER(1),
  PRIMARY KEY (id)
);



CREATE TABLE col_sante (
  id INTEGER,
user_id VARCHAR,
  date TEXT(10),
  poids INTEGER,
  tour_de_taille_en_cm INTEGER,
  fréquence_cardiaque_par_minute INTEGER,
  tension_artérielle_systolique_prise_du_matin INTEGER,
  tension_artérielle_systolique_prise_du_soir INTEGER,
  tension_artérielle_diastolique_prise_du_matin INTEGER,
  tension_artérielle_diastolique_prise_du_soir INTEGER,
  symptomes_cardiovasculaires_en_quelques_mots VARCHAR(50),
  nombre_de_médicaments_pris_dans_la_journée INTEGER,
  oubli_de_prendre_les_médicaments_le_matin BOOLEAN,
  oubli_de_prendre_les_médicaments_le_soir BOOLEAN,
  effets_secondaires_remarqués BOOLEAN,
  symptomes_particuliers_remarqués BOOLEAN,
  effets_secondaires_et_ou_symptomes_particuliers_en_quelques_mots VARCHAR(50),
  consommation_dalcool BOOLEAN,
  grignotage_sucre BOOLEAN,
  grignotage_sale BOOLEAN,
  nombre_de_repas_pris_durant_la_journée INTEGER,
  quantité_deau_bue_en_litre INTEGER,
  quantité_dalcool_consommé_en_litre INTEGER,
  activité_physique_aujourdhui BOOLEAN,
  nature_de_votre_activité_physique VARCHAR(50),
  durée_de_lactivité_physique_en_minutes INTEGER,
  présence_de_dyspnée BOOLEAN,
  présence_dœdème BOOLEAN,
  présence_dépisode_infectieux BOOLEAN,
  présence_de_fièvre BOOLEAN,
  présence_de_palpitation BOOLEAN,
  présence_de_douleur_thoracique BOOLEAN,
  présence_de_malaise BOOLEAN,
  heure_de_début_des_palpitations TIME,
  durée_totale_des_palpitations_en_minutes INTEGER,
  heure_de_début_des_douleurs_thoraciques TIME,
  durée_totale_des_douleurs_thoraciques_en_minutes INTEGER,
  heure_de_début_des_malaises TIME,
  durée_totale_des_malaises_en_minutes INTEGER,
  PRIMARY KEY (id)
);